#pragma once
#include <windef.h>

#define DISKFILTER_WIN32_DEVICE_NAME_A	"\\\\.\\DiskFilter"
#define DISKFILTER_WIN32_DEVICE_NAME_W	L"\\\\.\\DiskFilter"

#define DISKFILTER_DOS_DEVICE_NAME_W	L"\\DosDevices\\DiskFilter"

#define DISKFILTER_DEVICE_NAME_W		L"\\Device\\DiskFilter"

#define FILE_DEVICE_DISKFLT			0x8000

#ifdef CTL_CODE
#undef CTL_CODE
#endif
#define CTL_CODE( DeviceType, Function, Method, Access ) (                 \
    ((DeviceType) << 16) | ((Access) << 14) | ((Function) << 2) | (Method) \
)
#define METHOD_BUFFERED                 0
#define MAKECODE(Function) (CTL_CODE(FILE_DEVICE_DISKFLT,Function,METHOD_BUFFERED,FILE_ANY_ACCESS))

#define DISKFILTER_IOCTL_DRIVER_CONTROL MAKECODE(0x1CFF)

#define DISKFILTER_DRIVER_VERSION 0x10000102

static const BYTE DiskFilter_AuthorizationContext[] = "2265EBC24AA8192537B24166AAFB07396E8D39B94B8A270A02D316751181867824AEAC5A83B8CEF7A0911EB486FA00EA199AEB37D55F5961F3D01158CA3D497C";

enum DISKFILTER_PROTECTION_FLAGS
{
	PROTECTION_DEFAULT_FLAGS = 0x00,
	PROTECTION_ENABLE = 0x01,
	PROTECTION_ALLOW_DRIVER_LOAD = 0x02,
	PROTECTION_DRIVER_WHITELIST = 0x04,
	PROTECTION_DRIVER_BLACKLIST = 0x08,
	PROTECTION_ENABLE_THAWSPACE = 0x10,
	PROTECTION_ALLOW_DIRECT_MOUNT = 0x20,
	PROTECTION_FLAG_MAX = 0xFF,
};

DEFINE_ENUM_FLAG_OPERATORS(DISKFILTER_PROTECTION_FLAGS)

#define DISKFILTER_CONFIG_MAGIC 0xD156F117

#define DISKFILTER_THAWSPACE_HIDE 0x80

#define DISKFILTER_MAKE_VOLNUM(disk, part) (((disk) & 0xFFFFu) | (((part) & 0xFFFFu) << 16))
#define DISKFILTER_DISKNUM_FROM_VOLNUM(vol) ((vol) & (unsigned short)0xFFFF)
#define DISKFILTER_PARTNUM_FROM_VOLNUM(vol) (((vol) >> 16) & (unsigned short)0xFFFF)

#pragma pack(push, 1)
typedef struct {
	DWORD Magic;
	DWORD Version;
	UCHAR Password[32];
	UCHAR ProtectionFlags;
	UCHAR ProtectVolumeCount;
	UINT ProtectVolume[255];
	UCHAR DriverCount;
	UCHAR DriverList[255][32];
	UCHAR ThawSpaceCount;
	WCHAR ThawSpacePath[26][MAX_PATH + 5];
	WCHAR DriverPath[255][MAX_PATH];
	UCHAR Reserved[106540];
} DISKFILTER_PROTECTION_CONFIG, *PDISKFILTER_PROTECTION_CONFIG;
#pragma pack(pop)

typedef struct {
	BYTE AuthorizationContext[128];
	WCHAR Password[64];
	UCHAR ControlCode;
	DISKFILTER_PROTECTION_CONFIG Config;
} DISKFILTER_CONTROL, *PDISKFILTER_CONTROL;

typedef struct {
	ULONGLONG BytesVolumeTotal;
	ULONGLONG BytesBufferTotal;
	ULONGLONG BytesUsed;
	ULONGLONG BytesFree;
} DISKFILTER_BUFFER_STATUS, *PDISKFILTER_BUFFER_STATUS;

typedef struct {
	BOOLEAN ProtectEnabled;
	BOOLEAN AllowDriverLoad;
	BOOLEAN DirectMountEnabled;
	UCHAR ProtectVolumeCount;
	UINT ProtectVolume[255];
} DISKFILTER_STATUS, *PDISKFILTER_STATUS;

#pragma pack(push, 1)
typedef struct {
	ULONG Number;
	WCHAR DriveLetter;
	ULONG DiskNumber;
	ULONG PartitionNumber;
	BOOLEAN ReadOnly;
} DISKFILTER_DIRECTDISK, *PDISKFILTER_DIRECTDISK;
#pragma pack(pop)

typedef struct {
	UCHAR MountVolumeCount;
	DISKFILTER_DIRECTDISK MountVolume[255];
} DISKFILTER_DIRECTDISK_STATUS, *PDISKFILTER_DIRECTDISK_STATUS;

#pragma pack(push, 1)
typedef struct {
	ULONG DiskNumber;
	ULONG PartitionNumber;
} DISKFILTER_SAVEDATA, *PDISKFILTER_SAVEDATA;
#pragma pack(pop)

typedef struct {
	UCHAR SaveDataCount;
	DISKFILTER_SAVEDATA SaveDataVolume[255];
} DISKFILTER_SAVEDATA_STATUS, *PDISKFILTER_SAVEDATA_STATUS;

#define DISKFILTER_CONTROL_GET_BUFFER_STATUS 0x00
#define DISKFILTER_CONTROL_GETCONFIG 0x01
#define DISKFILTER_CONTROL_SETCONFIG 0x02
#define DISKFILTER_CONTROL_GETSTATUS 0x03
#define DISKFILTER_CONTROL_ALLOW_DRIVER_LOAD 0x04
#define DISKFILTER_CONTROL_DENY_DRIVER_LOAD 0x05
#define DISKFILTER_CONTROL_MOUNT_DIRECT_DISK 0x06
#define DISKFILTER_CONTROL_UNMOUNT_DIRECT_DISK 0x07
#define DISKFILTER_CONTROL_GET_DIRECTDISK_STATUS 0x08
#define DISKFILTER_CONTROL_SET_SAVE_DATA 0x09
#define DISKFILTER_CONTROL_CANCEL_SAVE_DATA 0x0a
#define DISKFILTER_CONTROL_GET_SAVE_DATA 0x0b
